add header & buy-now-modal markup
STIg89/command-project-HTML-CSS pull request #20
Opened 2022-09-17 16:47 UTC by YuliyaKey

2022-09-17 18:32 UTC, STIg89 requested changes

2022-09-17 18:32 UTC, STIg89 commented on src/partials/header.html
> +        <a class="header-logo link" href="">
пропиши путь на индекс.хтмл

2022-09-17 18:32 UTC, STIg89 commented on src/partials/modal-buy-now.html
> +<div class="modal">
поменяй везде modal на modal-buy-now иначе вы начнете друг-друга перебивать. модалок то много

2022-09-18 08:10 UTC, YuliyaKey commented on src/partials/header.html
> +        <a class="header-logo link" href="">
ok

2022-09-18 08:10 UTC, YuliyaKey commented on src/partials/modal-buy-now.html
> +<div class="modal">
ok

2022-09-18 08:53 UTC, STIg89 approved these changes

2022-09-18 08:53 UTC, merged